### ISSUE TITLE
您好，关于您代码中，有一些问题想请教您

### ISSUE THREAD

**Issue by leidaguo** [ShawnBIT/AI-Challenger-Retinal-Edema-Segmentation#1]
你好，您在train_image.txt中文件类型为
![image](https://user-images.githubusercontent.com/29405786/51366784-72c71b00-1b22-11e9-96ef-04ea0bf6a4b0.png)
但原始文件是从1开始，后缀为.bmp
![image](https://user-images.githubusercontent.com/29405786/51366826-a1dd8c80-1b22-11e9-8e61-7697398ce4f2.png)
为什么要这样处理？
但是我将train_image.txt文件改为和原始文件一样的格式，会报这样的错误
![image](https://user-images.githubusercontent.com/29405786/51366905-14e70300-1b23-11e9-8824-1dd5827d3811.png)
![image](https://user-images.githubusercontent.com/29405786/51366926-37791c00-1b23-11e9-97e6-f96c27ec98ba.png)
这是什么原因呢？希望得到您的解答，感谢

**Comment by chencjGene** [comment]
The image in the folder "trans3channel_images" is generated by slices stacking. you may need to run:
"python data/utils/gen_image.py" first.

**Comment by leidaguo** [comment]
@chencjGene Thank you, the problem has been solved.
